name: Release Build

on:
  push:
    branches: [ releases/* ]
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release branch to build from (e.g., releases/v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_PULL_REQUEST_API_TOKEN: ${{ secrets.PULL_REQUEST_API_TOKEN }}
  X_SCHEME: ${{ vars.X_SCHEME }}
  X_PROJ_DIR: ${{ vars.X_PROJ_DIR }}
  X_WORKSPACE_DIR: ${{ vars.X_WORKSPACE_DIR }}
  RELEASE_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_branch || github.ref }}

jobs:
  # test:
  #   name: Test
  #   runs-on: macos-latest
    
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
      
  #   - name: Setup Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.2'
  #       bundler-cache: true
        
  #   - name: Setup Xcode
  #     uses: maxim-lobanov/setup-xcode@v1
  #     with:
  #       xcode-version: latest-stable
        
  #   - name: Install dependencies
  #     run: |
  #       bundle install
        
  #   - name: Run tests
  #     run: |
  #       bundle exec fastlane test
        
  # build:
  #   name: Build
  #   runs-on: macos-latest
  #   # needs: test
    
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #   - name: Setup Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.2'
  #       bundler-cache: true
        
  #   - name: Setup Xcode
  #     uses: maxim-lobanov/setup-xcode@v1
  #     with:
  #       xcode-version: latest-stable

  #   - name: Install dependencies
  #     run: |
  #       bundle install
        
  #   - name: Build app
  #     run: |
  #       bundle exec fastlane build
        
  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: ios-build
  #       path: build/
 
  release:
    name: Release
    runs-on: macos-latest
    # needs: build
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ env.RELEASE_BRANCH }}
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0
            
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.2'
            bundler-cache: true
            
        - name: Install dependencies
          run: |
            bundle install
        
        - name: Get push commits
          id: get_commits
          run: |
            if [ "${{ github.event_name }}" = "push" ]; then
              echo "=== All commits from github.event.commits ==="
              echo '${{ toJson(github.event.commits) }}' | jq -r '.[] | "Commit: \(.id)\nAuthor: \(.author.name) <\(.author.email)>\nMessage: \(.message)\n"'
              echo "=============================================="

              COMMITS=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[].id' | tr '\n' ',' | sed 's/,$//')
            else
              COMMITS=""
            fi
            echo "commits=${COMMITS}" >> $GITHUB_OUTPUT

        - name: Create pull request
          run: |
            bundle exec fastlane create_pr_from_release_branch_v2 commits:"${{ steps.get_commits.outputs.commits }}"

    