name: Release Build

on:
  push:
    branches: [ rls/* ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install dependencies
      run: |
        bundle install
        
    - name: Run tests
      run: |
        bundle exec fastlane test
        
  build:
    name: Build
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install dependencies
      run: |
        bundle install
        
    - name: Build app
      run: |
        bundle exec fastlane build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/
 
  release:
    name: Release
    runs-on: macos-latest
    needs: build
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
      
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.2'
            bundler-cache: true
            
        - name: Install dependencies
          run: |
            bundle install
        
        - name: Create pull request
          run: |
            bundle exec fastlane create_pr_from_release_branch
    
          
    